/* Shared reading list data — used by reading.html and notes.html */
window.READING_CATEGORIES = [
  { id: "world-models", title: "World Models", icon: "🌍", items: [
    "World Models (Ha & Schmidhuber, 2018)",
    "DreamerV1, V2, V3 — read all three to see the evolution",
    "TD-MPC and TD-MPC2",
    "IRIS — discrete tokenised world models",
    "DIAMOND — diffusion world models",
    "Genie and Genie 2",
    "UniSim",
    "JEPA, I-JEPA, V-JEPA — the full LeCun vision",
    "LeCun — A Path Towards Autonomous Machine Intelligence",
    "Action-conditioned video prediction",
    "Latent dynamics models vs pixel prediction",
    "Recurrent State-Space Models (RSSM)",
    "Structured State Spaces (S4, Mamba)"
  ]},
  { id: "open-ended", title: "Open-Ended Learning", icon: "∞", items: [
    "Open-Endedness is Essential for ASI (Clune, 2019)",
    "POET and Enhanced POET",
    "XLand and XLand-MiniGrid",
    "Minimal Criterion Coevolution",
    "Novelty Search (Lehman & Stanley)",
    "MAP-Elites",
    "Quality-Diversity optimisation survey",
    "OMNI-EPIC",
    "Raileanu's UCL open-endedness course",
    "The innovation engine concept",
    "Picbreeder and CPPNs",
    "Auto-curricula and self-play",
    "Asymmetric self-play for goal discovery"
  ]},
  { id: "curiosity", title: "Curiosity & Exploration", icon: "🔭", items: [
    "ICM — Curiosity-driven Exploration",
    "Random Network Distillation (RND)",
    "Plan2Explore — curiosity meets world models",
    "Go-Explore",
    "BYOL-Explore",
    "Never Give Up (NGU)",
    "Agent57",
    "Count-based exploration",
    "Information gain as intrinsic motivation",
    "Empowerment as intrinsic motivation",
    "Active inference and free energy principle",
    "Frontier-based exploration in robotics",
    "Information-theoretic planning"
  ]},
  { id: "rl", title: "RL Foundations", icon: "🎯", items: [
    "Policy gradients — REINFORCE, PPO, TRPO",
    "Actor-critic — A2C, A3C, SAC",
    "Model-based RL landscape",
    "Offline RL — CQL, IQL, Decision Transformer",
    "Goal-conditioned RL",
    "Hierarchical RL — Options, HIRO, feudal networks",
    "Multi-task RL and generalisation",
    "Reward shaping and reward hacking",
    "Distributional RL",
    "Inverse RL — learning from demonstrations"
  ]},
  { id: "foundation-robotics", title: "Foundation Models for Robotics", icon: "🤖", items: [
    "RT-1, RT-2, RT-X",
    "Octo",
    "OpenVLA",
    "SayCan — LLMs as high-level planners",
    "Inner Monologue",
    "PaLM-E — embodied multimodal LM",
    "Code as Policies",
    "VoxPoser",
    "Language-conditioned imitation learning",
    "Vision-Language-Action models stack",
    "RoboFlamingo",
    "Generalist vs specialist robot policies"
  ]},
  { id: "vlm", title: "Vision-Language Models", icon: "👁", items: [
    "CLIP",
    "BLIP and BLIP-2",
    "LLaVA",
    "GPT-4V/4o vision capabilities",
    "SAM and SAM2 — segment anything",
    "Grounding DINO",
    "Open-vocabulary detection",
    "Vision Transformers (ViT)",
    "DINOv2",
    "MAE — masked autoencoders",
    "Multimodal fusion — early, late, cross-attention"
  ]},
  { id: "representation", title: "Representation Learning", icon: "🧬", items: [
    "Contrastive learning — SimCLR, MoCo, BYOL",
    "Joint embedding — VICReg, Barlow Twins",
    "Self-supervised learning for robotics",
    "Good representations for control",
    "Disentangled representations",
    "NeRF — Neural Radiance Fields",
    "3D Gaussian Splatting",
    "PointNet, PointNet++",
    "Occupancy networks",
    "Scene representations for robotics"
  ]},
  { id: "transformers", title: "Transformers & Attention", icon: "⚡", items: [
    "Attention Is All You Need — reread",
    "Multi-head attention mechanics",
    "Positional encodings — sinusoidal, RoPE, ALiBi",
    "Flash Attention",
    "State space models — Mamba, S4",
    "Mixture of experts",
    "KV-cache and efficient inference",
    "Sparse attention patterns",
    "Cross-attention for multi-modal fusion",
    "Perceiver and Perceiver IO"
  ]},
  { id: "locomotion", title: "Legged Locomotion", icon: "🦿", items: [
    "Quadruped gaits — walk, trot, gallop, bound",
    "Contact dynamics and ground reaction forces",
    "Whole-body control",
    "Central pattern generators",
    "RL for locomotion",
    "Rapid Motor Adaptation (Kumar et al.)",
    "Quadrupedal locomotion on challenging terrain",
    "Extreme parkour with legged robots",
    "Sim-to-real for locomotion",
    "Terrain classification and traversability",
    "Proprioception vs exteroception"
  ]},
  { id: "perception", title: "Perception for Robotics", icon: "📡", items: [
    "SLAM — visual, LiDAR, multi-modal",
    "Visual odometry",
    "LiDAR processing — FAST-LIO, FAST-LIO2",
    "Semantic SLAM — ConceptFusion, OpenScene",
    "Hydra — hierarchical scene graphs",
    "BEV representations",
    "Depth estimation — stereo, monocular",
    "Sensor fusion — Kalman, factor graphs, attention",
    "3D instance segmentation",
    "Place recognition and loop closure",
    "Active SLAM — where to look next"
  ]},
  { id: "sim2real", title: "Sim-to-Real Transfer", icon: "🔄", items: [
    "Domain randomisation",
    "Domain adaptation",
    "System identification",
    "Digital twins",
    "The sim-to-real gap",
    "NVIDIA Isaac Sim and Omniverse",
    "MuJoCo ecosystem",
    "Gazebo",
    "URLab (from your lab!)",
    "PyBullet",
    "When sim helps and where it fails"
  ]},
  { id: "planning", title: "Planning & Decision-Making", icon: "🗺", items: [
    "Classical planning — A*, RRT, RRT*, PRM",
    "Trajectory optimisation",
    "Model Predictive Control",
    "Diffusion for planning — Diffuser",
    "DiPPeR — from your lab",
    "Planning with learned models",
    "Task and motion planning (TAMP)",
    "Belief space planning",
    "Monte Carlo Tree Search for robotics",
    "Information-theoretic planning"
  ]},
  { id: "multiagent", title: "Multi-Agent & Swarms", icon: "🐝", items: [
    "Multi-agent RL — MAPPO, QMIX, MADDPG",
    "Communication in multi-agent systems",
    "Emergent communication",
    "Multi-robot exploration and coordination",
    "Adversarial multi-agent dynamics",
    "Swarm intelligence — flocking, foraging",
    "Decentralised decision-making",
    "Multi-robot SLAM"
  ]},
  { id: "continual", title: "Continual & Meta-Learning", icon: "🔁", items: [
    "Catastrophic forgetting",
    "Elastic Weight Consolidation",
    "Progressive Neural Networks",
    "MAML, Reptile, Prototypical Networks",
    "Few-shot learning for robotics",
    "Context-conditional adaptation",
    "Online learning and adaptation",
    "Learning to learn dynamics models",
    "Rapid adaptation for locomotion"
  ]},
  { id: "qd", title: "Quality-Diversity & Evolution", icon: "🧪", items: [
    "Robots that adapt like animals (Cully, Nature)",
    "MAP-Elites algorithm",
    "CMA-ME",
    "Differentiable Quality-Diversity",
    "Behavioural repertoires for damage recovery",
    "Novelty search with local competition",
    "NEAT, HyperNEAT",
    "Evolution strategies — OpenAI ES, CMA-ES",
    "Evolutionary open-ended learning"
  ]},
  { id: "cyber", title: "Cyber-Physical Security", icon: "🛡", items: [
    "Software-defined radio basics",
    "Network anomaly detection",
    "Adversarial attacks on robot perception",
    "Sensor spoofing and countermeasures",
    "Communication-aware planning",
    "Resilient autonomy under jamming",
    "Cyber-physical threat modelling",
    "Attack graphs for autonomous systems"
  ]},
  { id: "efficient", title: "Efficient ML", icon: "⚙", items: [
    "Knowledge distillation",
    "Pruning and quantisation",
    "Mixture of experts",
    "LoRA and parameter-efficient fine-tuning",
    "Gradient checkpointing, mixed precision",
    "TinyML and edge deployment",
    "Neural architecture search",
    "Sample-efficient RL",
    "DeepSeek's efficiency innovations"
  ]},
  { id: "uncertainty", title: "Bayesian & Uncertainty", icon: "📊", items: [
    "MC Dropout, deep ensembles",
    "Evidential deep learning",
    "Conformal prediction (you know this!)",
    "Gaussian processes for robotics",
    "Epistemic vs aleatoric uncertainty",
    "Uncertainty-aware planning",
    "Out-of-distribution detection",
    "Neural network calibration"
  ]},
  { id: "diffusion", title: "Diffusion Models", icon: "🌊", items: [
    "DDPM fundamentals",
    "Score-based generative modelling",
    "Diffusion for planning and decisions",
    "Stable Diffusion, DALL-E",
    "Video generation — Sora, Runway",
    "Diffusion for 3D generation",
    "Diffusion policies for robotics",
    "Classifier-free guidance"
  ]},
  { id: "extreme", title: "Extreme Environment Robotics", icon: "🚀", items: [
    "Mars rover autonomy — Perseverance, Curiosity",
    "Lunar robotics and Artemis",
    "Dragonfly Titan mission",
    "Autonomous underwater vehicles",
    "Sonar-based perception",
    "Subsea navigation without GPS",
    "Nuclear decommissioning robotics",
    "Robots in radiation environments",
    "Search and rescue robotics"
  ]}
];

window.READING_GROUPS = {
  all:      { label: "all",       ids: null },
  core:     { label: "core",      ids: ["world-models", "open-ended", "curiosity", "rl"] },
  robotics: { label: "robotics",  ids: ["foundation-robotics", "locomotion", "perception", "sim2real", "planning"] },
  ml:       { label: "ml",        ids: ["vlm", "representation", "transformers", "efficient", "diffusion", "uncertainty"] },
  frontier: { label: "frontier",  ids: ["multiagent", "continual", "qd", "cyber", "extreme", "open-ended"] },
};

window.READING_STORAGE_KEY = "ahmed-reading-list-v1";
